import re, sys, json
from playwright.sync_api import sync_playwright, expect
BASE = "http://localhost:5055"; errors = []; results = []
def ok(name, cond=True):
    results.append((name, bool(cond))); print(("PASS " if cond else "FAIL ") + name)
def wire(page):
    page.on("pageerror", lambda e: errors.append("pageerror: " + str(e)))
    page.on("console", lambda m: errors.append("console: " + m.text) if m.type == "error" and "fonts.g" not in m.text and "ERR_" not in m.text and "Failed to load resource" not in m.text else None)
def fill(page, scope, **kw):
    for k, v in kw.items():
        el = page.locator(f"{scope} [name={k}]")
        (el.select_option(v) if el.evaluate("e=>e.tagName") == "SELECT" else el.fill(v))
with sync_playwright() as p:
    b = p.chromium.launch(); ctx = b.new_context(viewport={"width": 1366, "height": 850}, permissions=["clipboard-read", "clipboard-write"]); page = ctx.new_page(); wire(page)
    page.goto(BASE)
    # --- register ---
    page.get_by_role("tab", name="Create account").click()
    fill(page, "form", garage_name="Kamau Motors", name="James Kamau", phone="0712345678", kra_pin="A123456789Z", email="james@kamau.co.ke", password="Secret123")
    page.get_by_role("button", name="Create garage account").click()
    expect(page.locator("nav.rail .who b")).to_have_text("Kamau Motors"); ok("register + auto sign-in")
    # validation error shown inline
    page.get_by_role("button", name="Sign out").click(); page.get_by_role("tab", name="Create account").click()
    fill(page, "form", garage_name="X", name="Y", phone="123", email="a@b.co", password="Secret123"); page.get_by_role("button", name="Create garage account").click()
    expect(page.locator("label.bad .err")).to_contain_text("valid Kenyan phone"); ok("inline field validation (bad phone)")
    page.get_by_role("tab", name="Sign in").click(); fill(page, "form", email="james@kamau.co.ke", password="wrongpass1"); page.get_by_role("button", name="Sign in").click()
    expect(page.locator(".toast.bad")).to_contain_text("incorrect"); ok("wrong password rejected")
    fill(page, "form", email="james@kamau.co.ke", password="Secret123"); page.get_by_role("button", name="Sign in").click()
    expect(page.locator("nav.rail .who b")).to_have_text("Kamau Motors"); ok("sign in")
    # --- team ---
    page.locator("nav.rail [data-page=team]").click()
    for nm, em in (("Otieno", "otieno@kamau.co.ke"), ("Mwangi", "mwangi@kamau.co.ke")):
        page.locator("#add-user").click(); fill(page, ".modal", name=nm, phone="0722111333", email=em, role="mechanic", password="Fundi12345"); page.locator(".modal button[type=submit]").click()
        expect(page.locator(".panel.tbl").first.locator("tbody tr", has_text=em)).to_be_visible()
    ok("add two mechanics")
    # --- stock ---
    page.locator("nav.rail [data-page=stock]").click(); expect(page.locator(".empty")).to_contain_text("store is empty"); ok("empty state for stock")
    page.locator("#add-part-btn").click(); fill(page, ".modal", sku="OIL-5W30", name="Engine oil 5W-30 1L", category="Oils", supplier="Toyota Kenya", unit_cost="800", sell_price="1200", qty="10", reorder_level="3"); page.locator(".modal button[type=submit]").click()
    expect(page.locator("tr[data-sku=OIL-5W30]")).to_be_visible(); ok("add part")
    page.locator("#add-part-btn").click(); fill(page, ".modal", sku="oil-5w30", name="dup", unit_cost="1", sell_price="2"); page.locator(".modal button[type=submit]").click()
    expect(page.locator(".modal label.bad .err")).to_contain_text("already exists"); ok("duplicate SKU blocked"); page.keyboard.press("Escape")
    page.locator("tr[data-sku=OIL-5W30] [data-act=adjust]").click(); fill(page, ".modal", reason="damaged", delta="-20"); page.locator(".modal button[type=submit]").click()
    expect(page.locator(".modal label.bad .err")).to_contain_text("Only 10 in stock"); ok("cannot remove more stock than exists"); page.keyboard.press("Escape")
    page.locator("tr[data-sku=OIL-5W30] [data-act=adjust]").click(); fill(page, ".modal", reason="received", delta="5", ref="DN-4421"); page.locator(".modal button[type=submit]").click()
    expect(page.locator("tr[data-sku=OIL-5W30] td.right.num").nth(0)).to_contain_text("15"); ok("receive stock (10 -> 15)")
    # --- vehicle ---
    page.locator("nav.rail [data-page=vehicles]").click(); page.locator("#add-vehicle").click()
    fill(page, ".modal", plate="kda 123a", customer_name="Wanjiku Njeri", phone="0700 111 222", make="Toyota", model="Axio", year="2015", mileage="80000"); page.locator(".modal button[type=submit]").click()
    expect(page.locator("tbody tr", has_text="Wanjiku")).to_be_visible(); ok("register vehicle (plate normalised)")
    page.locator("#vehicle-search").fill("wanj"); expect(page.locator("tbody tr")).to_have_count(1); ok("vehicle search by owner")
    # --- job ---
    page.locator("nav.rail [data-page=workshop]").click(); page.locator("#new-job").click()
    page.locator(".modal [name=vq]").fill("KDA"); page.locator(".sugg button", has_text="KDA123A").click()
    fill(page, ".modal", complaint="Brakes squeal and car pulls left", mileage_in="80500", fuel_level="1/2", belongings="Spare wheel"); page.locator(".modal [name=mechanic_id]").select_option(label="Otieno" if False else None) if False else None
    page.locator(".modal [name=mechanic_id] option", has_text="Otieno").evaluate("o=>{o.parentElement.value=o.value}")
    page.locator(".modal button[type=submit]").click()
    d = page.locator(".drawer"); expect(d.locator("h1")).to_have_text("JC-00001"); ok("create job card JC-00001")
    d.get_by_role("button", name="Start diagnosis").click(); expect(d.locator(".pill")).to_have_text("Diagnosing"); ok("intake -> diagnosing")
    d.locator("#part-search").fill("engine oil"); d.locator(".sugg button").first.click(); d.locator("input[aria-label=Quantity]").fill("2"); d.locator("#add-part").click()
    expect(d.locator("tbody tr", has_text="Engine oil")).to_be_visible(); ok("add part to job")
    d.locator("#labour-desc").fill("Brake pad replacement"); d.locator("#labour-price").fill("2500"); d.locator("#add-labour").click()
    expect(d.locator("[data-total]")).to_have_attribute("data-total", "5684"); ok("totals incl 16% VAT = 5,684")
    d.get_by_role("button", name="Send for quote").click(); expect(d.locator(".pill")).to_have_text("Quoted"); ok("diagnosing -> quoted")
    d.locator("#copy-link").click(); link = page.evaluate("navigator.clipboard.readText()"); ok("quote link copied", "/q/" in link)
    ok("WhatsApp share link built", "wa.me/254700111222" in d.get_by_role("link", name="Send on WhatsApp").get_attribute("href"))
    # customer opens the link on their own phone (separate context, no login)
    cust = b.new_context(viewport={"width": 390, "height": 800}).new_page(); wire(cust); cust.goto(link)
    expect(cust.locator("h1")).to_contain_text("JC-00001"); expect(cust.locator("tfoot")).to_contain_text("5,684"); ok("customer sees public quote, no login")
    cust.screenshot(path="/tmp/shot_quote_mobile.png")
    cust.locator("#approve-btn").click(); expect(cust.locator("h1")).to_contain_text("Approved"); ok("customer approves via link")
    cust.reload(); expect(cust.locator("h1")).to_contain_text("unavailable"); ok("quote link is single-use")
    d.get_by_role("button", name="Close").click(); page.locator(".card[data-job=JC-00001]").click(); d = page.locator(".drawer")
    expect(d.locator(".pill")).to_have_text("Approved"); ok("job shows Approved after customer link")
    d.get_by_role("button", name="Start repair").click(); expect(d.locator(".pill")).to_have_text("In repair"); ok("approved -> in repair")
    d.locator("#labour-desc").fill("Rotor skim"); d.locator("#labour-price").fill("1000"); d.locator("#add-labour").click()
    expect(d.locator("#reapproval")).to_be_visible(); ok("extra work triggers re-approval banner")
    d.locator("#diagnosis").fill("Pads worn to metal. Rotors skimmed."); d.locator("#save-diag").click()
    d.get_by_role("button", name="Send to quality check").click(); expect(d.locator(".pill")).to_have_text("Quality check"); ok("in repair -> QA")
    d.get_by_role("button", name="Mark ready for pickup").click(); expect(page.locator(".toast.bad")).to_contain_text("Extra work"); ok("cannot mark ready with unapproved extra work")
    d.locator("#reapproval #record-approval").click(); page.locator(".modal button[type=submit]").click(); expect(d.locator("#reapproval")).to_have_count(0); ok("record approval clears banner")
    d.get_by_role("button", name="Mark ready for pickup").click(); expect(d.locator(".pill")).to_have_text("Ready for pickup"); ok("QA -> ready")
    ok("no stray 'null'/'undefined' text in drawer", not re.search(r"\\b(null|undefined)\\b", page.locator(".drawer").inner_text()))
    page.screenshot(path="/tmp/shot_drawer.png")
    d.locator("#make-invoice").click(); inv = page.locator(".modal.printable"); expect(inv).to_contain_text("INV-00001"); expect(inv.locator("[data-balance]")).to_have_attribute("data-balance", "6844"); ok("invoice created, total KES 6,844")
    inv.locator("[name=reference]").fill("bad"); inv.locator("[name=amount]").fill("4000"); inv.locator("#record-payment").click(); expect(inv.locator("label.bad .err")).to_contain_text("10 letters"); ok("M-Pesa code validated")
    inv.locator("[name=reference]").fill("SGH7K2L9QP"); inv.locator("#record-payment").click(); expect(inv.locator("[data-balance]")).to_have_attribute("data-balance", "2844"); ok("partial M-Pesa payment")
    inv.locator("[name=method]").select_option("cash"); inv.locator("[name=amount]").fill("2844"); inv.locator("#record-payment").click(); expect(inv.locator("[data-balance]")).to_have_attribute("data-balance", "0"); ok("cash settles invoice")
    inv.locator("[name=etims_ref]").fill("KRACU0100001234/5678"); inv.get_by_role("button", name="Save").click(); expect(page.locator(".toast", has_text="eTIMS number saved")).to_be_visible(); ok("eTIMS number saved on invoice")
    page.keyboard.press("Escape"); expect(page.locator(".modal.printable")).to_have_count(0); expect(page.locator(".drawer .pill")).to_have_text("Invoiced"); ok("job shows Invoiced behind invoice")
    page.keyboard.press("Escape"); expect(page.locator(".drawer")).to_have_count(0)
    # stock deducted
    page.locator("nav.rail [data-page=stock]").click(); expect(page.locator("tr[data-sku=OIL-5W30] td.right.num").nth(0)).to_contain_text("13"); ok("stock deducted by job (15 -> 13)")
    page.locator("nav.rail [data-page=invoices]").click(); expect(page.locator("tr[data-inv=INV-00001]")).to_contain_text("Paid"); ok("invoice list shows Paid")
    page.locator("nav.rail [data-page=team]").click(); expect(page.locator("main h1")).to_have_text("Team"); ok("no stray 'null' text on pages", not re.search(r"\\b(null|undefined)\\b", page.locator("main").inner_text()))
    page.locator("nav.rail [data-page=reports]").click(); k = page.locator("#kpis"); expect(k).to_contain_text("6,844"); expect(k).to_contain_text("Collected"); ok("report: collected KES 6,844")
    expect(page.locator("svg[aria-label='Daily collections'] rect")).to_have_count(1); ok("report chart renders")
    page.screenshot(path="/tmp/shot_reports.png")
    # second job for mechanic scope test
    page.locator("nav.rail [data-page=vehicles]").click(); page.locator("#add-vehicle").click(); fill(page, ".modal", plate="KCB 777Z", customer_name="Ali Hassan", phone="0733444555", make="Nissan", model="Note"); page.locator(".modal button[type=submit]").click()
    page.locator("nav.rail [data-page=workshop]").click(); page.locator("#new-job").click(); page.locator(".modal [name=vq]").fill("KCB"); page.locator(".sugg button", has_text="KCB777Z").click(); fill(page, ".modal", complaint="Overheating")
    page.locator(".modal [name=mechanic_id] option", has_text="Otieno").evaluate("o=>{o.parentElement.value=o.value}"); page.locator(".modal button[type=submit]").click(); expect(page.locator(".drawer h1")).to_have_text("JC-00002"); page.keyboard.press("Escape")
    page.screenshot(path="/tmp/shot_board.png")
    page.get_by_role("button", name="Sign out").click()
    # --- mechanic view ---
    fill(page, "form", email="otieno@kamau.co.ke", password="Fundi12345"); page.get_by_role("button", name="Sign in").click()
    expect(page.locator("h1")).to_have_text("My jobs"); ok("mechanic lands on My jobs")
    ok("mechanic sees only own job", page.locator(".card").count() == 1)
    ok("mechanic nav has no Reports/Invoices/Team", page.locator("nav.rail [data-page=reports], nav.rail [data-page=invoices], nav.rail [data-page=team]").count() == 0)
    ok("mechanic board shows no prices", "KES" not in page.locator(".board").inner_text())
    page.locator(".card").click(); d = page.locator(".drawer"); ok("mechanic drawer has no price/labour controls", d.locator("#add-labour").count() == 0 and "KES" not in d.inner_text())
    d.get_by_role("button", name="Start diagnosis").click(); expect(d.locator(".pill")).to_have_text("Diagnosing"); ok("mechanic can progress own job")
    page.keyboard.press("Escape"); page.locator("nav.rail [data-page=stock]").click(); ok("mechanic stock view hides cost & adjust", page.locator("th", has_text="Cost").count() == 0 and page.locator("[data-act=adjust]").count() == 0)
    # mobile layout
    m = b.new_context(viewport={"width": 390, "height": 800}).new_page(); wire(m); m.goto(BASE)
    fill(m, "form", email="james@kamau.co.ke", password="Secret123"); m.get_by_role("button", name="Sign in").click(); expect(m.locator("#new-job")).to_be_visible()
    ok("mobile: no horizontal page overflow", m.evaluate("document.documentElement.scrollWidth <= window.innerWidth + 1")); m.screenshot(path="/tmp/shot_mobile.png")
    ok("mobile: bottom nav visible", m.locator("nav.rail").bounding_box()["y"] > 600)
    # XSS attempt renders as text
    page.get_by_role("button", name="Sign out").click(); fill(page, "form", email="james@kamau.co.ke", password="Secret123"); page.get_by_role("button", name="Sign in").click()
    page.locator("nav.rail [data-page=vehicles]").click(); page.locator("#add-vehicle").click(); fill(page, ".modal", plate="KDD 999X", customer_name="<img src=x onerror=window.__xss=1>", phone="0711000999"); page.locator(".modal button[type=submit]").click()
    expect(page.locator("tbody tr", has_text="<img")).to_be_visible(); ok("XSS payload shown as inert text", page.evaluate("window.__xss") is None)
    b.close()
print("\nconsole/page errors:", errors or "none"); ok("no JS errors in browser", not errors)
bad = [n for n, c in results if not c]; print(f"\n{len(results)-len(bad)}/{len(results)} checks passed"); sys.exit(1 if bad else 0)
